# Minimal Fluid theme config overrides
# https://github.com/fluid-dev/hexo-theme-fluid

navbar:
  blog_title: 味儿福德詹的小站
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "ai", name: "AI", link: "/categories/AI/", icon: "iconfont icon-category-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

index:
  slogan:
    enable: false

post:
  meta:
    date_format: "YYYY-MM-DD"

search:
  enable: true
  path: /local-search.xml
